// Schema for the operator-toggled policy capture written by
// `bebop-linux`. Each tick of the 100 Hz control loop produces one
// `PolicyCaptureSample`; the runner serializes it and ships it through
// a bounded mpsc channel to a dedicated MCAP writer thread (see
// `firmware/bebop-linux/src/policy_capture.rs`).
//
// The capture file is an MCAP container with this proto's
// `FileDescriptorSet` embedded as the schema. Foxglove and any
// off-the-shelf MCAP reader can plot individual scalar fields
// (e.g. `quat_w`, `joint_pos_rad[3]`) without our app's protobuf
// definitions.
//
// Codegen: `prost-build` picks this up via the glob in `build.rs`. The
// app does NOT need this proto — captures are robot-side files; the
// app only sees the `policy_io.capture_active` / `capture_path` /
// `capture_rows` fields from `bebop_runtime.proto`.

// @generated by protoc-gen-es v2.12.0 with parameter "target=ts,import_extension=js"
// @generated from file bebop_capture.proto (package bebop.capture.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file bebop_capture.proto.
 */
export const file_bebop_capture: GenFile = /*@__PURE__*/
  fileDesc("ChNiZWJvcF9jYXB0dXJlLnByb3RvEhBiZWJvcC5jYXB0dXJlLnYxIpsDChNQb2xpY3lDYXB0dXJlU2FtcGxlEgwKBHRpY2sYASABKAQSFAoMd2FsbF90aW1lX25zGAIgASgEEhIKCnNpbV90aW1lX3MYAyABKAESDAoEbW9kZRgKIAEoCRIPCgdkcnlfcnVuGAsgASgIEhAKCGltdV9saXZlGAwgASgIEg4KBnF1YXRfeBgUIAEoAhIOCgZxdWF0X3kYFSABKAISDgoGcXVhdF96GBYgASgCEg4KBnF1YXRfdxgXIAEoAhIRCglhbmdfdmVsX3gYGCABKAISEQoJYW5nX3ZlbF95GBkgASgCEhEKCWFuZ192ZWxfehgaIAEoAhIVCg1qb2ludF9wb3NfcmFkGB4gAygCEhcKD2pvaW50X3ZlbF9yYWRfcxgfIAMoAhITCgtqb2ludF9hcm1lZBggIAMoCBITCgtvYnNlcnZhdGlvbhgoIAMoAhISCgpyYXdfYWN0aW9uGCkgAygCEhwKFHBvc2l0aW9uX3RhcmdldHNfcmFkGDIgAygCEgoKAmtwGDMgAygCEgoKAmtkGDQgAygCYgZwcm90bzM");

/**
 * One per 100 Hz tick of the control loop while capture is active.
 * Layout chosen for trivial Foxglove Plot panel use:
 *   * scalar IMU components surface as their own plot paths
 *     (`/policy_capture/quat_w`, `/policy_capture/ang_vel_x`, ...);
 *   * high-dim arrays use `repeated float` whose indices map 1:1 to the
 *     policy slot order documented in
 *     `firmware/bebop-linux/src/observation.rs::JOINT_NAMES`.
 *
 * In DIAL_IN mode the policy is NOT inferring; the action-related
 * `repeated` fields (`raw_action`, `position_targets_rad`, `kp`, `kd`)
 * are left empty so the schema is identical in both modes — readers
 * just see length-0 arrays.
 *
 * @generated from message bebop.capture.v1.PolicyCaptureSample
 */
export type PolicyCaptureSample = Message<"bebop.capture.v1.PolicyCaptureSample"> & {
  /**
   * Monotonic tick counter starting at 0 when capture opens. Survives
   * mode transitions within a single capture file.
   *
   * @generated from field: uint64 tick = 1;
   */
  tick: bigint;

  /**
   * Wall-clock time, nanoseconds since the Unix epoch. The MCAP header's
   * `log_time` carries the same value (so Foxglove time scrubbing
   * works), but we also record it inline for jitter analysis without
   * having to re-parse MCAP records.
   *
   * @generated from field: uint64 wall_time_ns = 2;
   */
  wallTimeNs: bigint;

  /**
   * Monotonic seconds since the capture file was opened. Useful as a
   * self-contained x-axis when the operator just wants to plot a single
   * file in isolation.
   *
   * @generated from field: double sim_time_s = 3;
   */
  simTimeS: number;

  /**
   * Operating mode at this tick: "IDLE" (capture started but bench is
   * idle), "DIAL_IN" (obs only — no action fields), "RUN_POLICY"
   * (full obs + action).
   *
   * @generated from field: string mode = 10;
   */
  mode: string;

  /**
   * Operator dry-run flag. When `true`, RUN_POLICY produced an action
   * (recorded in this sample) but the supervisor did NOT TX it to the
   * motors.
   *
   * @generated from field: bool dry_run = 11;
   */
  dryRun: boolean;

  /**
   * True when the BNO snapshot used for this tick's observation was
   * within its freshness budget (rotation vector + gyro arrive on the
   * same SH-2 channel so a single liveness flag covers both).
   *
   * @generated from field: bool imu_live = 12;
   */
  imuLive: boolean;

  /**
   * IMU body-frame orientation, Hamilton (XYZW, scalar last); identity
   * is `(0, 0, 0, 1)`. Already mount-rotated into REP-103 / FLU body
   * frame upstream by the IMU thread.
   *
   * @generated from field: float quat_x = 20;
   */
  quatX: number;

  /**
   * @generated from field: float quat_y = 21;
   */
  quatY: number;

  /**
   * @generated from field: float quat_z = 22;
   */
  quatZ: number;

  /**
   * @generated from field: float quat_w = 23;
   */
  quatW: number;

  /**
   * Body-frame angular velocity (rad/s, FLU).
   *
   * @generated from field: float ang_vel_x = 24;
   */
  angVelX: number;

  /**
   * @generated from field: float ang_vel_y = 25;
   */
  angVelY: number;

  /**
   * @generated from field: float ang_vel_z = 26;
   */
  angVelZ: number;

  /**
   * Per-joint state in policy slot order (8 entries, see JOINT_NAMES).
   * `joint_armed[i]` is the operator's per-joint enable at this tick
   * (false when the motor is disabled — the supervisor ignores TX for
   * those joints in RUN_POLICY).
   *
   * @generated from field: repeated float joint_pos_rad = 30;
   */
  jointPosRad: number[];

  /**
   * @generated from field: repeated float joint_vel_rad_s = 31;
   */
  jointVelRadS: number[];

  /**
   * @generated from field: repeated bool joint_armed = 32;
   */
  jointArmed: boolean[];

  /**
   * Full 49-element observation fed to ONNX on this tick. Layout matches
   * `bebop.runtime.v1.PolicyIoStats.observation` (see comment there for
   * slice boundaries).
   *
   * @generated from field: repeated float observation = 40;
   */
  observation: number[];

  /**
   * Full 24-element raw NN output. Empty in DIAL_IN.
   *
   * @generated from field: repeated float raw_action = 41;
   */
  rawAction: number[];

  /**
   * Decoded MIT-mode commands (8 joints, policy slot order). Empty in
   * DIAL_IN.
   *
   * @generated from field: repeated float position_targets_rad = 50;
   */
  positionTargetsRad: number[];

  /**
   * @generated from field: repeated float kp = 51;
   */
  kp: number[];

  /**
   * @generated from field: repeated float kd = 52;
   */
  kd: number[];
};

/**
 * Describes the message bebop.capture.v1.PolicyCaptureSample.
 * Use `create(PolicyCaptureSampleSchema)` to create a new message.
 */
export const PolicyCaptureSampleSchema: GenMessage<PolicyCaptureSample> = /*@__PURE__*/
  messageDesc(file_bebop_capture, 0);

