# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: navd/telemetry.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14navd/telemetry.proto\x12\nbebop.navd\"1\n\x05Twist\x12\n\n\x02vx\x18\x01 \x01(\x01\x12\n\n\x02wz\x18\x02 \x01(\x01\x12\x10\n\x08stamp_ns\x18\x03 \x01(\x03\"=\n\x04Odom\x12\t\n\x01x\x18\x01 \x01(\x01\x12\t\n\x01y\x18\x02 \x01(\x01\x12\r\n\x05theta\x18\x03 \x01(\x01\x12\x10\n\x08stamp_ns\x18\x04 \x01(\x03\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'navd.telemetry_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _TWIST._serialized_start=36
  _TWIST._serialized_end=85
  _ODOM._serialized_start=87
  _ODOM._serialized_end=148
# @@protoc_insertion_point(module_scope)
