//! Shared wire-format crate.
//!
//! - [`v1`] — BLE control surface used by `bebop-agent` and the Tauri app
//!   for one-shot setup / provisioning / lifecycle requests.
//! - [`runtime::v1`] — protobuf-over-WebSocket runtime API exposed by
//!   `bebop-linux` for live motor control and telemetry.
//! - [`capture::v1`] — schema for the MCAP capture files written by
//!   `bebop-linux` while the operator has policy capture enabled.
//!
//! All types are generated by [`prost`] from the `.proto` files in
//! `bebop-proto/proto/` (see `build.rs`).

pub mod v1 {
    include!(concat!(env!("OUT_DIR"), "/bebop.v1.rs"));
}

pub mod runtime {
    pub mod v1 {
        include!(concat!(env!("OUT_DIR"), "/bebop.runtime.v1.rs"));
    }
}

pub mod capture {
    pub mod v1 {
        include!(concat!(env!("OUT_DIR"), "/bebop.capture.v1.rs"));
    }
}

/// Combined `FileDescriptorSet` for every proto compiled by this crate,
/// serialized to its `protoc --descriptor_set_out` byte form.
///
/// The MCAP writer in `bebop-linux` embeds this as the schema record at
/// the head of each capture file (MCAP's well-known `protobuf` schema
/// encoding expects `data = FileDescriptorSet` bytes for the root
/// message and all of its dependencies). Carrying the FDS unconditionally
/// means a fresh MCAP file is self-describing — Foxglove / mcap-cli /
/// any reader can decode the messages without needing our `.proto`
/// sources on disk.
///
/// Including all three protos (BLE + runtime + capture) costs a few KB
/// of overhead per capture file; we accept that for the build simplicity
/// of a single descriptor-set emission step in `build.rs`.
pub const FILE_DESCRIPTOR_SET: &[u8] =
    include_bytes!(concat!(env!("OUT_DIR"), "/descriptor.bin"));

pub use prost::Message;
