//! Shared wire-format crate.
//!
//! - [`v1`] — BLE control surface used by `bebop-agent` and the Tauri app
//!   for one-shot setup / provisioning / lifecycle requests.
//! - [`runtime::v1`] — protobuf-over-WebSocket runtime API exposed by
//!   `bebop-linux` for live motor control and telemetry.
//!
//! All types are generated by [`prost`] from the `.proto` files in
//! `bebop-proto/proto/` (see `build.rs`).

pub mod v1 {
    include!(concat!(env!("OUT_DIR"), "/bebop.v1.rs"));
}

pub mod runtime {
    pub mod v1 {
        include!(concat!(env!("OUT_DIR"), "/bebop.runtime.v1.rs"));
    }
}

pub use prost::Message;
